# Welcome to NumPy tutorial

NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices. 

NumPy stands for Numerical Python.

#### Why Use NumPy?
In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.

### Why is NumPy Faster Than Lists?
NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

### Which Language is NumPy written in?
NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.



In [3]:
import numpy as np

In [4]:
print("Hello, World!")

Hello, World!


In [5]:
i = 45

In [6]:
i # markdown tutorial --> not very much useful for a data scientist

45

**Now from here numpy starts**

In [7]:
import numpy as np

In [8]:
myarr1 = np.array([3,6,32,7], np.int8) # we have created a 1D numpy array 
# we have provided a type integer of size 8 bit.
# Therefore, this array will not take any number besides integers and of size mores than 8 bit.

In [9]:
myarr1

array([ 3,  6, 32,  7], dtype=int8)

In [10]:
myarr1[1]

6

In [11]:
myarr2 = np.array([[3,6,32,7]], np.int64) # we have created a 2D numpy array 
# we have provided a type integer of size 64 bit.
# Therefore, this array will not take any number besides integers and of size mores than 64 bit.

In [12]:
myarr2[0,1] # accessing element of zeroth row and 1st column

6

In [13]:
myarr1.shape # to know the info of any numpy array

(4,)

In [14]:
myarr2.shape

(1, 4)

In [15]:
myarr1.dtype

dtype('int8')

In [16]:
myarr2.dtype  # search numpy types reference

dtype('int64')

In [17]:
myarr2[0,1]

6

In [18]:
myarr2[0,1] = 45 # to change the element

In [19]:
myarr2

array([[ 3, 45, 32,  7]], dtype=int64)

*search --> array creation methods in numpy*

**There are 5 general mechanism for creating arrays:**

## 1) Array creation : Conversion from other Python structures

In [20]:
listarray = np.array([[1,2,3], [5,8,5], [0,3,1]])

In [21]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [22]:
listarray.dtype

dtype('int32')

In [23]:
listarray.shape

(3, 3)

In [24]:
listarray.size

9

In [26]:
# Creating a array of dictionary
d = np.array({34,23,55})
# But creating this type of arrays (dtype object) is not considered to be efficient, generally float and int type is used 

In [30]:
d

array({34, 55, 23}, dtype=object)

## 2) Intrinsic numpy array creation objects (e.g., arange, ones, zeros, etc.)

In [36]:
# zeroes = np.zeroes((2,5))

In [32]:
#zeroes

In [33]:
#zeroes.dtype

In [34]:
#zeroes.shape

In [37]:
rng = np.arange(15) # it will not give list, it will give array

In [38]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [39]:
lspace = np.linspace(1,5,12)

In [40]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [41]:
emp = np.empty((4,6)) # it will give an array of empty of size 4,6 with random values

In [42]:
emp

array([[6.23042070e-307, 3.56043053e-307, 1.60219306e-306,
        7.56571288e-307, 1.89146896e-307, 1.37961302e-306],
       [1.05699242e-307, 8.01097889e-307, 1.78020169e-306,
        7.56601165e-307, 1.02359984e-306, 1.33510679e-306],
       [2.22522597e-306, 1.33511018e-306, 6.23057689e-307,
        1.86921279e-306, 8.90098127e-307, 1.78020848e-306],
       [1.60219035e-306, 1.42418172e-306, 2.04712906e-306,
        7.56589622e-307, 1.11258277e-307, 8.90111708e-307]])

In [43]:
emp_like = np.empty_like(lspace)

In [44]:
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [45]:
ide = np.identity(45) # will create a identity matrix of size 45X45

In [46]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [47]:
ide.shape

(45, 45)

In [48]:
arr = np.arange(99)

In [49]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [50]:
arr.reshape(3, 33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [52]:
# arr.reshape(3,31) # will throw error because 3,31 is not possible or cant be reshaped with 99

In [53]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [54]:
arr = arr.reshape(3, 33)

In [55]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [56]:
arr = arr.ravel()

In [57]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [58]:
arr.shape

(99,)

**Numpy Axis**

In [59]:
x = [[1,2,3], [4,5,6], [7,1,0]]

In [60]:
ar = np.array(x)

In [61]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [62]:
ar.sum(axis=0) # axis=0 means rows

array([12,  8,  9])

In [63]:
ar.sum(axis=1) # axis=0 means columns

array([ 6, 15,  8])

In [64]:
ar.T # it will transpose the array

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [65]:
ar.flat

In [66]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [67]:
ar.ndim # number of dimensions

2

In [68]:
ar.size

9

In [69]:
ar.nbytes # total bytes consumed by the array

36

These above all are attributes of numpy array

In [70]:
one = np.array([1,3,4,645,2])

In [71]:
one.argmax() # it will give the index of the maximum element

# function (or method)--> when bracket is used, attributes--> without bracket

3

In [72]:
one.argmin()

0

In [73]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

Now same functions for 2D array

In [74]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [75]:
ar.argmin()

8

In [76]:
ar.argmax()

6

In [77]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [78]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [79]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [80]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [81]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [82]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [83]:
ar.reshape(9,)

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

Now mathematical operations in arrays which numpy provides

MATRIX OPERATIONS

In [84]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [85]:
ar2 = np.array([[1, 4, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [86]:
ar + ar2

array([[ 2,  6,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [87]:
[324, 34] + [34, 546] # the same process (sum) in list cant be done, it will extend the list

[324, 34, 34, 546]

In [88]:
ar * ar2

array([[ 1,  8,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [89]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [90]:
ar.sum() # sum all the elements

29

In [91]:
ar.max()

7

In [92]:
ar.min()

0

In [93]:
np.where(ar>5) # to find the elements in the array and will return a tuple

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

[1,2] is 6 and [2,0] is 7

In [94]:
type(np.where(ar>5))

tuple

In [95]:
np.count_nonzero(ar) # count non zero numbers

8

In [96]:
np.nonzero(ar) # it will return tuple for each dimension and position 

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [97]:
ar[1,2] = 0

In [98]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int64))

In [99]:
import sys

In [100]:
py_ar = [0,4,55,2]

In [101]:
np_ar = np.array(py_ar)

In [102]:
sys.getsizeof(1)

28

### Extra

In [103]:
# creating an array with 10^7 elements
arr = np.arange(1e7)
arr

array([0.000000e+00, 1.000000e+00, 2.000000e+00, ..., 9.999997e+06,
       9.999998e+06, 9.999999e+06])

In [104]:
# creating an ndarray to list
larr = arr.tolist()
larr

[0.0,
 1.0,
 2.0,
 3.0,
 4.0,
 5.0,
 6.0,
 7.0,
 8.0,
 9.0,
 10.0,
 11.0,
 12.0,
 13.0,
 14.0,
 15.0,
 16.0,
 17.0,
 18.0,
 19.0,
 20.0,
 21.0,
 22.0,
 23.0,
 24.0,
 25.0,
 26.0,
 27.0,
 28.0,
 29.0,
 30.0,
 31.0,
 32.0,
 33.0,
 34.0,
 35.0,
 36.0,
 37.0,
 38.0,
 39.0,
 40.0,
 41.0,
 42.0,
 43.0,
 44.0,
 45.0,
 46.0,
 47.0,
 48.0,
 49.0,
 50.0,
 51.0,
 52.0,
 53.0,
 54.0,
 55.0,
 56.0,
 57.0,
 58.0,
 59.0,
 60.0,
 61.0,
 62.0,
 63.0,
 64.0,
 65.0,
 66.0,
 67.0,
 68.0,
 69.0,
 70.0,
 71.0,
 72.0,
 73.0,
 74.0,
 75.0,
 76.0,
 77.0,
 78.0,
 79.0,
 80.0,
 81.0,
 82.0,
 83.0,
 84.0,
 85.0,
 86.0,
 87.0,
 88.0,
 89.0,
 90.0,
 91.0,
 92.0,
 93.0,
 94.0,
 95.0,
 96.0,
 97.0,
 98.0,
 99.0,
 100.0,
 101.0,
 102.0,
 103.0,
 104.0,
 105.0,
 106.0,
 107.0,
 108.0,
 109.0,
 110.0,
 111.0,
 112.0,
 113.0,
 114.0,
 115.0,
 116.0,
 117.0,
 118.0,
 119.0,
 120.0,
 121.0,
 122.0,
 123.0,
 124.0,
 125.0,
 126.0,
 127.0,
 128.0,
 129.0,
 130.0,
 131.0,
 132.0,
 133.0,
 134.0,
 135.0,
 136.0,
 137.0,
 138.0

In [105]:
%timeit # magic functions

In [106]:
# converting ndarray to  list
arr = np.arange(10,100)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [107]:
arr = np.linspace(0,1,100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [109]:
ar = np.array([3,6,32,7])
dir(ar)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [116]:
# sum(dir(ar))
# dir(ar).shape
# dir(ar).sum()
len(dir(ar))

162

In [117]:
# from see import see
# see(ar)

For More refer to:- https://www.w3schools.com/python/numpy/default.asp  

or https://numpy.org/doc/stable/user/absolute_beginners.html